apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-service-check
  namespace: cloud-operations
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: http-service-check
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: http-service-check
        deploymentconfig: http-service-check
    spec:
      containers:
        - image: image:tag
          imagePullPolicy: IfNotPresent
          name: http-service-check
          resources: {}
          env:
            - name: endpoint
              value: "https://example.google.com"
            - name: ExpectedStatusCode
              value: "200"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
